
# Project-wide Gradle settings.

# Required for any project using AndroidX dependencies (appcompat, material, etc.)
android.useAndroidX=true

# Default value: true; overridden for clarity.
android.enableJetifier=false

# AndroidX package structure to make it clearer which packages are bundled
# with the Android operating system, and which are packaged with your app's
# APK. This property specifies the JVM heap size used by the Gradle daemon.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
