package com.ankita.h2sdosimeter.model;

/**
 * ExposureRecord - represents one badge scan / exposure reading.
 *
 * IMPORTANT SAFETY NOTE:
 * The "estimatedExposureDisplay" field is a DEMO/MOCK value during the
 * frontend phase. It does NOT represent a validated measurement of
 * H2S exposure. Real values require calibrated colorimetric analysis
 * and cannot be generated by this application at this stage.
 *
 * Do not use these values for occupational health decisions.
 */
public class ExposureRecord {

    public enum ExposureCategory {
        LOW, ELEVATED, HIGH, UNKNOWN
    }

    private String recordId;
    private String date;
    private String time;
    private String shiftName;
    private String badgeId;

    /**
     * Displayed as DEMO/MOCK - not a real measurement.
     * Format: "0.8 ppm.hr [ESTIMATED - DEMO]"
     */
    private String estimatedExposureDisplay;

    private ExposureCategory category;
    private Badge.BadgeStatus badgeStatus;
    private String imageQuality;
    private boolean lightingCorrectionApplied;
    private boolean isMockData;

    public ExposureRecord(String recordId, String date, String time,
                          String shiftName, String badgeId,
                          String estimatedExposureDisplay,
                          ExposureCategory category,
                          Badge.BadgeStatus badgeStatus) {
        this.recordId = recordId;
        this.date = date;
        this.time = time;
        this.shiftName = shiftName;
        this.badgeId = badgeId;
        this.estimatedExposureDisplay = estimatedExposureDisplay;
        this.category = category;
        this.badgeStatus = badgeStatus;
        this.imageQuality = "Good";
        this.lightingCorrectionApplied = true;
        this.isMockData = true; // always true during frontend phase
    }

    public String getRecordId() { return recordId; }
    public String getDate() { return date; }
    public String getTime() { return time; }
    public String getShiftName() { return shiftName; }
    public String getBadgeId() { return badgeId; }
    public String getEstimatedExposureDisplay() { return estimatedExposureDisplay; }
    public ExposureCategory getCategory() { return category; }
    public Badge.BadgeStatus getBadgeStatus() { return badgeStatus; }
    public String getImageQuality() { return imageQuality; }
    public boolean isLightingCorrectionApplied() { return lightingCorrectionApplied; }
    public boolean isMockData() { return isMockData; }

    public void setRecordId(String recordId) { this.recordId = recordId; }
    public void setDate(String date) { this.date = date; }
    public void setTime(String time) { this.time = time; }
    public void setShiftName(String shiftName) { this.shiftName = shiftName; }
    public void setBadgeId(String badgeId) { this.badgeId = badgeId; }
    public void setEstimatedExposureDisplay(String v) { this.estimatedExposureDisplay = v; }
    public void setCategory(ExposureCategory category) { this.category = category; }
    public void setBadgeStatus(Badge.BadgeStatus badgeStatus) { this.badgeStatus = badgeStatus; }
    public void setImageQuality(String imageQuality) { this.imageQuality = imageQuality; }
    public void setLightingCorrectionApplied(boolean v) { this.lightingCorrectionApplied = v; }
}
